version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: nest-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: nestjsrealworld
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080